# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Character.create([
{ name: 'Batman', universe: 'dc', difficulty: '1'},
{ name: 'Superman', universe: 'dc', difficulty: '1'},
{ name: 'Wonder Woman', universe: 'dc', difficulty: '1'},
{ name: 'The Flash', universe: 'dc', difficulty: '1'},
{ name: 'Green Arrow', universe: 'dc', difficulty: '1'},
{ name: 'Robin', universe: 'dc', difficulty: '1'},
{ name: 'Supergirl', universe: 'dc', difficulty: '1'},
{ name: 'Catwoman', universe: 'dc', difficulty: '1'},
{ name: 'Aquaman', universe: 'dc', difficulty: '1'},
{ name: 'Green Lantern', universe: 'dc', difficulty: '1'},
{ name: 'Cyborg', universe: 'dc', difficulty: '1'},
{ name: 'Hawkgirl ', universe: 'dc', difficulty: '1'},
{ name: 'Beast Boy', universe: 'dc', difficulty: '1'},
{ name: 'Raven', universe: 'dc', difficulty: '1'},
{ name: 'Starfire', universe: 'dc', difficulty: '1'},
{ name: 'Katana', universe: 'dc', difficulty: '1'},
{ name: 'Martian Manhunter', universe: 'dc', difficulty: '1'},
{ name: 'Rick Flag', universe: 'dc', difficulty: '1'},
{ name: 'Shazam', universe: 'dc', difficulty: '1'},
{ name: 'Nightwing', universe: 'dc', difficulty: '1'},
{ name: 'Joker', universe: 'dc', difficulty: '1'},
{ name: 'Lex Luthor', universe: 'dc', difficulty: '1'},
{ name: 'Ra\'s al Ghul', universe: 'dc', difficulty: '1'},
{ name: 'Harley Quinn', universe: 'dc', difficulty: '1'},
{ name: 'Bane', universe: 'dc', difficulty: '1'},
{ name: 'Scarecrow', universe: 'dc', difficulty: '1'},
{ name: 'Deadshot', universe: 'dc', difficulty: '1'},
{ name: 'Reverse-Flash', universe: 'dc', difficulty: '1'},
{ name: 'Two-Face', universe: 'dc', difficulty: '1'},
{ name: 'DeathStroke', universe: 'dc', difficulty: '1'},
{ name: 'Penguin', universe: 'dc', difficulty: '1'},
{ name: 'Riddler', universe: 'dc', difficulty: '1'},
{ name: 'Doomsday', universe: 'dc', difficulty: '1'},
{ name: 'Zod', universe: 'dc', difficulty: '1'},
{ name: 'Killer Croc', universe: 'dc', difficulty: '1'},
{ name: 'Enchantress', universe: 'dc', difficulty: '1'},
{ name: 'El Diablo', universe: 'dc', difficulty: '1'},
{ name: 'Captain Boomerang', universe: 'dc', difficulty: '1'},
{ name: 'Mr. Freeze', universe: 'dc', difficulty: '1'},
{ name: 'Poison Ivy', universe: 'dc', difficulty: '1'},
{ name: 'Iron Man', universe: 'marvel', difficulty: '1'},
{ name: 'Spider-Man', universe: 'marvel', difficulty: '1'},
{ name: 'Thor', universe: 'marvel', difficulty: '1'},
{ name: 'Captian America', universe: 'marvel', difficulty: '1'},
{ name: 'Hulk', universe: 'marvel', difficulty: '1'},
{ name: 'Black Widow', universe: 'marvel', difficulty: '1'},
{ name: 'Hawkeye', universe: 'marvel', difficulty: '1'},
{ name: 'Professor X', universe: 'marvel', difficulty: '1'},
{ name: 'Wolverine', universe: 'marvel', difficulty: '1'},
{ name: 'Beast', universe: 'marvel', difficulty: '1'},
{ name: 'Deadpool', universe: 'marvel', difficulty: '1'},
{ name: 'Doctor Strange', universe: 'marvel', difficulty: '1'},
{ name: 'Ant-Man', universe: 'marvel', difficulty: '1'},
{ name: 'Falcon', universe: 'marvel', difficulty: '1'},
{ name: 'Quicksilver', universe: 'marvel', difficulty: '1'},
{ name: 'Black Panther', universe: 'marvel', difficulty: '1'},
{ name: 'Mister Fantastic', universe: 'marvel', difficulty: '1'},
{ name: 'Daredevil', universe: 'marvel', difficulty: '1'},
{ name: 'Jessica Jones', universe: 'marvel', difficulty: '1'},
{ name: 'Scarlet Witch', universe: 'marvel', difficulty: '1'},
{ name: 'Magneto', universe: 'marvel', difficulty: '1'},
{ name: 'Green Goblin', universe: 'marvel', difficulty: '1'},
{ name: 'Loki', universe: 'marvel', difficulty: '1'},
{ name: 'Red Skull', universe: 'marvel', difficulty: '1'},
{ name: 'Mystique', universe: 'marvel', difficulty: '1'},
{ name: 'Thanos', universe: 'marvel', difficulty: '1'},
{ name: 'Ronan', universe: 'marvel', difficulty: '1'},
{ name: 'Doctor Doom', universe: 'marvel', difficulty: '1'},
{ name: 'Doctor Octopus', universe: 'marvel', difficulty: '1'},
{ name: 'Venom', universe: 'marvel', difficulty: '1'},
{ name: 'Winter Soldier', universe: 'marvel', difficulty: '1'},
{ name: 'Iron Monger', universe: 'marvel', difficulty: '1'},
{ name: 'Apocalypse', universe: 'marvel', difficulty: '1'},
{ name: 'Punisher', universe: 'marvel', difficulty: '1'},
{ name: 'Silver Surfer', universe: 'marvel', difficulty: '1'},
{ name: 'Galactus', universe: 'marvel', difficulty: '1'},
{ name: 'Laufey', universe: 'marvel', difficulty: '1'},
{ name: 'Kingpin', universe: 'marvel', difficulty: '1'},
{ name: 'Sandman', universe: 'marvel', difficulty: '1'},
{ name: 'Abomination', universe: 'marvel', difficulty: '1'},







])
